apiVersion: v1
kind: Pod
metadata:
  name: multi-container-pod
spec:
  nodeName: ip-192-168-85-103.ap-southeast-1.compute.internal
  containers:
  - name: first-container
    image: nginx
  - name: second-container
    image: tomcat:8
