apiVersion: v1
kind: PersistentVolume
metadata:
  name: task-pv-30-volume
  labels:
    type: aws
spec:
  storageClassName: manual
  capacity:
    storage: 30Gi
  accessModes:
    - ReadWriteOnce
  awsElasticBlockStore:
    volumeID: "vol-0c8045e317aaadf4f"
    fsType: ext4
