apiVersion: apps/v1
kind: Deployment
metadata:
  name: first-deployment
spec:
  selector:
    matchLabels:
      a: america
  replicas: 4
  template:
    metadata:
      labels:
        a: america
    spec:
      containers:
      - name: nginx
        image: nginx
        envFrom:
        - configMapRef:
           name: second-cm
